'use strict'

const config = require('../config')
const env = process.env.NODE_ENV === 'development' ? config.dev.env : config.build.env
const host = env.HOST
const prefix = host + '/manage/'

export default {
    my: prefix + 'my/',
    logout: host + '/logout/',
    static: host + '/static/',
    member: prefix + 'member/',
    memberapplication: prefix + 'memberapplication/',
    agent: prefix + 'agent/',
    agentapplication: prefix + 'agentapplication/',
    level: prefix + 'level/',
    provider: prefix + 'provider/',
    provider_setting: prefix + 'provider_setting/',
    return: prefix + 'returnsetting/',
    bank: prefix + 'bank/',
    agentlevel: prefix + 'agentlevel/',
    commission: prefix + 'commissionsetting/',
    register: prefix + 'register/member/',
    onlinepayee: prefix + 'onlinepayee/',
    bill: prefix + 'transaction/',
    login: prefix + 'login/',
    agentlogin: host + '/agent/login/',
    remitpayee: prefix + 'remitpayee/',
    loginrecord: prefix + 'loginrecord/',
    paymentgateway: prefix + 'paymentgateway/',
    onlinemembers: prefix + 'online_member/',
    transactiontype: prefix + 'transaction_type/',
    manual_transaction: prefix + 'manual_transaction/',
    resetmember: prefix + 'password/member/',
    resetagent: prefix + 'password/agent/',
    resetwithdraw: prefix + 'withdraw_password/member/',
    betrecords: prefix + 'betrecord/',
    gameaccounts: prefix + 'gameaccount/',
    gameprovider: host + '/member/provider/',
    transferrecords: prefix + 'transferrecord/',
    staff: prefix + 'staff/',
    managerole: prefix + 'group/',
    refresh_token: prefix + 'login/refresh/',
    promotion: prefix + 'promotion/',
    permissionsUser: prefix + 'permissions/user/',
    returnrate: prefix + 'report/returnrate/',
    passwordstaff: prefix + 'password/staff/',
    checktype: host + '/checktype/',
    platform_report: prefix + 'report/platform/',
    game_report: prefix + 'report/game/',
    gamecategory: prefix + 'gamecategory/',
    returnhistory: prefix + 'report/returnrate/history/',
    returnratedetail: prefix + 'report/returnrate/detail/',
    reportcommission: prefix + 'report/commission/',
    transactionwithdraw: prefix + 'transaction/withdraw/',
    transactiononlinepay: prefix + 'transaction/onlinepayment/',
    returnreport: host + '/report/',
    transactioncommission: prefix + 'transaction/withdraw/',
    banner: prefix + 'banners/',
    announcement: prefix + 'announcements/',
    permissions: prefix + 'permissions/',
    staffPermissions: prefix + 'staff/permissions/',
    website: prefix + 'website/home-page/',
    paymenttype: prefix + 'paymenttype/'

}
